#lang typed-scheme
(require "bankers-deque-tests.ss"
         "bankers-queue-tests.ss"
         "binary-ran-access-list-tests.ss"
         "binomialheap-tests.ss"
         "bootstrapedheap-tests.ss"
         "bootstrapedqueue-tests.ss"
         "catenablelist-tests.ss"
         "hood-melville-queue-tests.ss"
         "implicitdeque-tests.ss"
         "implicitqueue-tests.ss"
         "lazypairingheap-test.ss"
         "leftistheaps-tests.ss"
         "pairingheap-test.ss"
         "physicists-queue-tests.ss"
         "realtimedeque-tests.ss"
         "realtimequeue-tests.ss"
         "redblacktrees-tests.ss"
         "skewbinaryrandomaccesslist-tests.ss"
         "skewbinomialheap-tests.ss"
         "splayheap-tests.ss"
         "stream-tests.ss"
         "tries-test.ss"
         "vlist-tests.ss")