#lang typed-scheme
(require "bankers-deque-tests.rkt"
         "bankers-queue-tests.rkt"
         "binary-ran-access-list-tests.rkt"
         "binomialheap-tests.rkt"
         "bootstrapedheap-tests.rkt"
         "bootstrapedqueue-tests.rkt"
         "catenablelist-tests.rkt"
         "hood-melville-queue-tests.rkt"
         "implicitdeque-tests.rkt"
         "implicitqueue-tests.rkt"
         "lazypairingheap-test.rkt"
         "leftistheaps-tests.rkt"
         "pairingheap-test.rkt"
         "physicists-queue-tests.rkt"
         "realtimedeque-tests.rkt"
         "realtimequeue-tests.rkt"
         "redblacktrees-tests.rkt"
         "skewbinaryrandomaccesslist-tests.rkt"
         "skewbinomialheap-tests.rkt"
         "splayheap-tests.rkt"
         "stream-tests.rkt"
         "tries-test.rkt"
         "vlist-tests.rkt")
